### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by sebaahoue** [HE-Arc/eduardo#14]

**Comment by daviddasilva1** [comment]
css dans la page de création de compte ajouté 1bc56c9143dddf3cfd42f95112c072de3e27f267

**Comment by daviddasilva1** [comment]
css dans la page de login ajouté 80a20556b09c78c9d98ba1b706bc793488241fbb

**Comment by daviddasilva1** [comment]
le css dans les formulaires de login/création de compte ont été ajoutés. 1bc56c9143dddf3cfd42f95112c072de3e27f267
